version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.22.1
    - 8.24.0
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.14
    - 2.5.9
    - 2.6.0
    - 2.7.0
    - 2.8.2
    - 2.8.3
  - dependency-name: nunomaduro/collision
    versions:
    - 5.3.0
    - 5.4.0
  - dependency-name: laravel/sanctum
    versions:
    - 2.9.0
    - 2.9.1
    - 2.9.2
    - 2.9.3
    - 2.9.4
  - dependency-name: fakerphp/faker
    versions:
    - 1.13.0
    - 1.14.0
    - 1.14.1
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
  - dependency-name: spatie/laravel-permission
    versions:
    - 4.0.0
    - 4.0.1
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
    - 2.6.1
  - dependency-name: mockery/mockery
    versions:
    - 1.4.3
  - dependency-name: renatomarinho/laravel-page-speed
    versions:
    - 2.0.0
- package-ecosystem: npm
  directory: "/package.json"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
